project-tracker backend/README.md, project-tracker backend/config/database.json, project-tracker backend/config/jwt.json, project-tracker backend/config/swagger.json, project-tracker backend/package-lock.json, project-tracker backend/package.json, project-tracker backend/src/app/controllers/login.ts, project-tracker backend/src/app/models/user.ts, project-tracker backend/src/app/routers/index.ts, project-tracker backend/src/app/routers/login.ts, project-tracker backend/src/app/serializers/login.ts, project-tracker backend/src/app/serializers/user.ts, project-tracker backend/src/index.ts, project-tracker backend/src/lib/authentication.ts, project-tracker backend/src/lib/roles.ts
Added index, login router,
User model,
login controller,
login and user serializer,
authentication middleware
=> I13 authentication

frontend/theta-project-tracker/src/app/components/new-user.component.ts, frontend/theta-project-tracker/src/app/components/users.component.ts, frontend/theta-project-tracker/src/app/modals/delete-modal.component.ts, frontend/theta-project-tracker/src/app/modals/new-user-modal.component.ts, frontend/theta-project-tracker/src/app/models/user.model.ts, frontend/theta-project-tracker/src/app/resolvers/user.resolver.ts, frontend/theta-project-tracker/src/app/services/user.service.ts
created basic user listing, new user component and delete modal
l
=> I35 add new user

frontend/theta-project-tracker/src/app/app.module.ts, frontend/theta-project-tracker/src/app/components/users.component.ts
Added pagination to users component.
=> I87 pagination

backend/config/swagger.json, backend/src/app/controllers/login.ts, backend/src/app/controllers/projectUser.ts, backend/src/app/controllers/user.ts, backend/src/app/controllers/userProfile.ts, backend/src/app/routers/index.ts, backend/src/app/routers/user.ts, backend/src/app/routers/userProfile.ts, backend/src/app/serializers/login.ts
this branch depends on pr #109 (i96-user-profile)
PUT /user/profile
if got newPassword, update it,
if got newEmail, update it
current password is required
removed PUT /user/:id from user's accessible endpoints
=> I111 profile update

backend/config/swagger.json, backend/src/app/controllers/login.ts, backend/src/app/controllers/projectUser.ts, backend/src/app/controllers/user.ts, backend/src/app/controllers/userProfile.ts, backend/src/app/routers/index.ts, backend/src/app/routers/user.ts, backend/src/app/routers/userProfile.ts, backend/src/app/serializers/login.ts
added GET user/profile resource
it sends back the logged in user's data
also added try-catch to projectUsers controller --> now works properly
=> i96-user-profile

frontend/theta-project-tracker/src/app/app.module.ts, frontend/theta-project-tracker/src/app/components/header.component.ts, frontend/theta-project-tracker/src/app/components/login.component.ts, frontend/theta-project-tracker/src/app/modals/confirm-modal.component.ts, frontend/theta-project-tracker/src/app/modals/confirm-modal.ts, frontend/theta-project-tracker/src/app/services/auth.service.ts, frontend/theta-project-tracker/src/assets/i18n/en.json
Added logout and confirmation modal to header and the logged in users first name now can be seen.
=> I31 logout

backend/config/swagger.json
Updated for with other status codes and actionLabel resource
+ query params
=> I117 swagger update

backend/config/swagger.json, backend/migrations/20200629154111_create_overtimeMultipliers.js, backend/seeds/08-example-overtimeMultipliers.js, backend/src/app/controllers/overtimeMultiplier.ts, backend/src/app/models/overtimeMultiplier.ts, backend/src/app/routers/index.ts, backend/src/app/routers/overtimeMultiplier.ts, backend/src/lib/enums.ts
Added new resource: overtimeMultiplier
created migration, seed
created crud, model, router
tested, works
conflict solved
sorry for the large pr, couldnt split it
=> I29 overtime multiplier resource

backend/config/swagger.json, backend/package-lock.json, backend/package.json, backend/src/app/controllers/calendar.ts, backend/src/app/routers/calendar.ts, backend/src/app/routers/index.ts
created resource GET /calendar
works with query params (year, month)
responses the whole month with date and its multiplier, according to overtimeMultiplier table
certainly not clean code, tried to refactor but could not, but at least it works
=> I130 days of the month

frontend/theta-project-tracker/src/app/app-routing.module.ts
Fixed issue regarding routing, so that a logged in users homepage isn't the login page.
=> I135 routing fix

frontend/theta-project-tracker/src/app/app-routing.module.ts, frontend/theta-project-tracker/src/app/app.module.ts, frontend/theta-project-tracker/src/app/components/edit-user.component.ts, frontend/theta-project-tracker/src/app/components/new-user.component.ts, frontend/theta-project-tracker/src/app/components/users.component.ts, frontend/theta-project-tracker/src/app/modals/new-user-modal.component.ts, frontend/theta-project-tracker/src/app/models/user.model.ts, frontend/theta-project-tracker/src/app/resolvers/milestone.resolver.ts, frontend/theta-project-tracker/src/app/resolvers/project.resolver.ts, frontend/theta-project-tracker/src/app/services/projectUsers.service.ts, frontend/theta-project-tracker/src/app/services/user.service.ts
user management is fully working with backend now
if it's accepted we could close user-, project-, milestone- and client epic issues
=> I1 user management

backend/config/swagger.json, backend/migrations/20200618151311_create_actionLabels.js, backend/seeds/06-example-actionLabels.js, backend/src/app/controllers/actionLabel.ts, backend/src/app/controllers/projectActionLabel.ts, backend/src/app/models/actionLabel.ts, backend/src/app/routers/index.ts, backend/src/app/routers/projectActionLabel.ts, backend/src/app/serializers/actionLabel.ts
edited migration:
projectId, soft-delete, unique
seed:
added 2 more examples
actionLabelController: 
soft-delete, serialization, some fix
created:
projectActionLabelController
/project/:projectId/actionLabel responses the labels of the given project
updated: swagger
=> i138 editactionLabel controller

backend/config/swagger.json, backend/src/app/controllers/milestone.ts, backend/src/app/controllers/projectMilestone.ts, backend/src/app/routers/index.ts, backend/src/app/routers/projectMilestone.ts, backend/src/app/serializers/milestone.ts
new resource: /project/milestone/:projectId
responses the given project's milestones
available for both user and admin
=> I134 milestones on project

backend/src/app/controllers/user.ts
response contains pageIndex, pageSize, count
first of all, testing on one resource
=> i140 index response

frontend/theta-project-tracker/src/app/app-routing.module.ts, frontend/theta-project-tracker/src/app/app.component.ts, frontend/theta-project-tracker/src/app/app.module.ts, frontend/theta-project-tracker/src/app/components/action-label.component.ts, frontend/theta-project-tracker/src/app/components/clients.component.ts, frontend/theta-project-tracker/src/app/components/milestones.component.ts, frontend/theta-project-tracker/src/app/components/new-action-label.component.ts, frontend/theta-project-tracker/src/app/components/new-milestone.component.ts, frontend/theta-project-tracker/src/app/components/new-project.component.ts, frontend/theta-project-tracker/src/app/components/projects.component.ts, frontend/theta-project-tracker/src/app/components/sidenav-container.component.ts, frontend/theta-project-tracker/src/app/components/users.component.ts, frontend/theta-project-tracker/src/app/modals/new-action-label-modal.component.ts, frontend/theta-project-tracker/src/app/models/action-label.model.ts, frontend/theta-project-tracker/src/app/resolvers/action-label.resolver.ts, frontend/theta-project-tracker/src/app/services/action-label.service.ts
create service, component, edit, delete, add action label
fix a little css
=> I141 action label

frontend/theta-project-tracker/src/app/app-routing.module.ts, frontend/theta-project-tracker/src/app/app.component.ts, frontend/theta-project-tracker/src/app/components/action-label.component.ts, frontend/theta-project-tracker/src/app/components/client-management-component.ts, frontend/theta-project-tracker/src/app/components/clients.component.ts, frontend/theta-project-tracker/src/app/components/edit-user.component.ts, frontend/theta-project-tracker/src/app/components/header.component.ts, frontend/theta-project-tracker/src/app/components/milestones.component.ts, frontend/theta-project-tracker/src/app/components/new-action-label.component.ts, frontend/theta-project-tracker/src/app/components/new-milestone.component.ts, frontend/theta-project-tracker/src/app/components/new-project.component.ts, frontend/theta-project-tracker/src/app/components/new-user.component.ts, frontend/theta-project-tracker/src/app/components/profile.component.ts, frontend/theta-project-tracker/src/app/components/projects.component.ts, frontend/theta-project-tracker/src/app/components/reports-table.component.ts, frontend/theta-project-tracker/src/app/components/reports.component.ts, frontend/theta-project-tracker/src/app/components/users.component.ts, frontend/theta-project-tracker/src/app/modals/confirm-modal.component.ts, frontend/theta-project-tracker/src/app/modals/delete-modal.component.ts, frontend/theta-project-tracker/src/app/services/client.service.ts, frontend/theta-project-tracker/src/app/services/project.service.ts, frontend/theta-project-tracker/src/app/services/projectUsers.service.ts, frontend/theta-project-tracker/src/app/services/user.service.ts, frontend/theta-project-tracker/src/assets/i18n/en.json
cursor fix on header if no one is logged in
recolored buttons
translated stuff, that wasn't translated
disabled buttons if forms are invalid
deleted unused imports, console.logs
tried to unify look
deleted space validators
=> I154-css-magic

frontend/theta-project-tracker/src/app/components/reports-table.component.ts, frontend/theta-project-tracker/src/app/components/reports.component.ts, frontend/theta-project-tracker/src/app/services/reports.service.ts
filtering works by users and projects
=> I151-report-filter

frontend/theta-project-tracker/package.json, frontend/theta-project-tracker/src/app/app.module.ts, frontend/theta-project-tracker/src/app/components/reports.component.ts, frontend/theta-project-tracker/src/app/services/reports.service.ts, frontend/theta-project-tracker/src/app/table/table.component.html
reports can be filtered by start and end dates
=> I158 reports date filters

backend/src/app/controllers/report.ts
=> I164 modified queries

backend/config/swagger.json, backend/migrations/20200704234350_create_userTimeRecord.js, backend/migrations/20200704234358_create_timeRecord.js, backend/seeds/08-example-userTimeRecord.js, backend/src/app/controllers/timeRecord.ts, backend/src/app/models/userTimeRecord.ts, backend/src/app/serializers/timeRecord.ts
=> timeRecord debug

frontend/theta-project-tracker/src/app/services/action-label.service.ts, frontend/theta-project-tracker/src/app/services/client.service.ts, frontend/theta-project-tracker/src/app/services/milestone.service.ts, frontend/theta-project-tracker/src/app/services/project.service.ts, frontend/theta-project-tracker/src/app/services/projectUsers.service.ts, frontend/theta-project-tracker/src/app/services/user.service.ts
http calls dont throw parsing errors
=> I181-http call fix

backend/migrations/20200617135856_create_projectUsers.js, backend/src/app/controllers/projectUser.ts
=> i178-projectUser-duplicate

backend/src/app/controllers/report.ts, backend/src/app/routers/report.ts, backend/src/app/serializers/report.ts, backend/src/lib/report.ts, backend/src/lib/reportQuery.ts
to avoid code duplication with exports, I had to reorganize code for reports
=> I175 reorganizing report generation

backend/config/swagger.json
=> I172 swagger for export endpoint

frontend/theta-project-tracker/src/app/components/action-label.component.ts, frontend/theta-project-tracker/src/app/components/date-picker.component.ts, frontend/theta-project-tracker/src/app/components/edit-user.component.ts, frontend/theta-project-tracker/src/app/components/new-user.component.ts, frontend/theta-project-tracker/src/app/components/projects.component.ts, frontend/theta-project-tracker/src/app/components/reports.component.ts, frontend/theta-project-tracker/src/app/components/sidenav-container.component.ts, frontend/theta-project-tracker/src/app/modals/add-user-to-project-modal.component.ts, frontend/theta-project-tracker/src/app/modals/delete-modal.component.ts, frontend/theta-project-tracker/src/assets/i18n/en.json
=> fixed internationalization

frontend/theta-project-tracker/src/app/components/new-user.component.ts, frontend/theta-project-tracker/src/app/components/profile.component.ts, frontend/theta-project-tracker/src/app/modals/add-user-to-project-modal.component.ts, frontend/theta-project-tracker/src/assets/i18n/en.json
=> I184-small-fixes

backend/config/swagger.json, backend/src/app/controllers/timeRecordCopy.ts
date is now in body, not in query
=> TimeRecord copy fix

backend/package-lock.json, backend/package.json, backend/src/lib/reportQuery.ts
table joins in report queries were wrong, fixed
(plus package.json update because we need excel4node)
=> I189 report join correction

frontend/theta-project-tracker/src/app/components/edit-user.component.ts, frontend/theta-project-tracker/src/app/components/new-user.component.ts, frontend/theta-project-tracker/src/app/modals/add-user-to-project-modal.component.ts, frontend/theta-project-tracker/src/app/models/project.model.ts, frontend/theta-project-tracker/src/app/models/user.model.ts, frontend/theta-project-tracker/src/app/services/projectUsers.service.ts
not really fixed, but some changes are needed
will not use this feature on demo
=> almost last finishes

frontend/theta-project-tracker/src/app/components/reports.component.ts, frontend/theta-project-tracker/src/app/services/reports.service.ts
=> I203 reports rewrite

backend/src/lib/reportQuery.ts
aliasing broke query transformation
=> I204 budget report bugfix
